version: '3.8'

services:
  steam-downloader:
    build: .
    ports:
      - "7860:7860"
      - "9090:9090"
    volumes:
      - ./downloads:/app/downloads
      - ./public:/app/public
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s 