version: '3.8'

services:
  steam-downloader:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - steam-data:/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

volumes:
  steam-data:
    driver: local