[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[mount]
source = "/data"
destination = "/app/downloads"

[[ports]]
port = "${PORT}"
internal = "${PORT}" 