[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.dockerfile"
buildCommand = "docker build -t steam-downloader ."

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
autoScaling = true
minReplicas = 1
maxReplicas = 3
targetMemoryUtilizationPercentage = 80
targetCPUUtilizationPercentage = 80

[[deploy.volumes]]
name = "steam-downloads"
mountPath = "/data"
size = "50Gi"

[deploy.envs]
LOG_LEVEL = "INFO"
ENABLE_METRICS = "true"
METRICS_PORT = "9090"

[[deploy.routes]]
domain = "steam-downloader.railway.app"
path = "/"

[mount]
source = "/data"
destination = "/app/downloads"

[[ports]]
port = "${PORT}"
internal = "${PORT}" 
